# Generated by Django 4.2.2 on 2023-06-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USUARIOS',
            fields=[
                ('Usuario', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Nom_Usu', models.CharField(max_length=20)),
                ('Ape_Usu', models.CharField(max_length=20)),
                ('Fec_Nac_usu', models.DateField()),
            ],
        ),
    ]
