# Generated by Django 4.2.2 on 2023-06-06 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ALIMENTOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_Ali', models.CharField(max_length=20)),
                ('Cal_Ali', models.IntegerField()),
                ('Img_Ali', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='TIP_ALIMENTOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_tip', models.CharField(max_length=20)),
                ('Des_Tip', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='REGISTRO_ALIMENTOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fec_reg', models.DateField()),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='REG_USUARIOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fec_Reg', models.DateField()),
                ('Est_Usu', models.FloatField()),
                ('Pes_Usu', models.FloatField()),
                ('Ind_Mas_Cor', models.FloatField(null=True)),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='DETALLE_ALIMENTOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cant_calo', models.FloatField(null=True)),
                ('Cod_Reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.registro_alimentos')),
                ('Id_Ali', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.alimentos')),
            ],
        ),
        migrations.AddField(
            model_name='alimentos',
            name='Cod_Tip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.tip_alimentos'),
        ),
    ]
