# Generated by Django 4.2.1 on 2023-07-18 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_administradores_usuarios_con_usu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ADMINISTRADORES',
        ),
        migrations.AlterModelOptions(
            name='alimentos',
            options={'verbose_name': 'Alimento', 'verbose_name_plural': 'Alimentos'},
        ),
        migrations.AlterModelOptions(
            name='detalle_alimentos',
            options={'verbose_name': 'Detalle de Alimentos Consumidos', 'verbose_name_plural': 'Detalles de Alimentos Consumidos'},
        ),
        migrations.AlterModelOptions(
            name='reg_usuarios',
            options={'verbose_name': 'Registros de IMC de Usuario', 'verbose_name_plural': 'Registros de IMC Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='registro_alimentos',
            options={'verbose_name': 'Registro de Alimentos Consumidos', 'verbose_name_plural': 'Registros de Alimentos Consumidos'},
        ),
        migrations.AlterModelOptions(
            name='tip_alimentos',
            options={'verbose_name': 'Tipo de Alimento', 'verbose_name_plural': 'Tipos de Alimentos'},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RemoveField(
            model_name='alimentos',
            name='Img_Ali',
        ),
        migrations.AddField(
            model_name='detalle_alimentos',
            name='Cantidad',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='alimentos',
            name='Cal_Ali',
            field=models.IntegerField(verbose_name='Calorias'),
        ),
        migrations.AlterField(
            model_name='alimentos',
            name='Cod_Tip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.tip_alimentos', verbose_name='Tipo de alimento'),
        ),
        migrations.AlterField(
            model_name='alimentos',
            name='Nom_Ali',
            field=models.CharField(max_length=20, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='detalle_alimentos',
            name='Cant_calo',
            field=models.FloatField(null=True, verbose_name='Total calorias'),
        ),
        migrations.AlterField(
            model_name='detalle_alimentos',
            name='Cod_Reg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.registro_alimentos', verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='detalle_alimentos',
            name='Id_Ali',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.alimentos', verbose_name='Alimento'),
        ),
        migrations.AlterField(
            model_name='reg_usuarios',
            name='Est_Usu',
            field=models.FloatField(verbose_name='Estatura'),
        ),
        migrations.AlterField(
            model_name='reg_usuarios',
            name='Fec_Reg',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='reg_usuarios',
            name='Ind_Mas_Cor',
            field=models.FloatField(null=True, verbose_name='IMC'),
        ),
        migrations.AlterField(
            model_name='reg_usuarios',
            name='Pes_Usu',
            field=models.FloatField(verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='registro_alimentos',
            name='Fec_reg',
            field=models.DateField(verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='tip_alimentos',
            name='Des_Tip',
            field=models.CharField(max_length=50, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='tip_alimentos',
            name='Nom_tip',
            field=models.CharField(max_length=20, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='Ape_Usu',
            field=models.CharField(max_length=20, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='Con_Usu',
            field=models.CharField(max_length=20, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='Fec_Nac_usu',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='Nom_Usu',
            field=models.CharField(max_length=20, verbose_name='Nombre'),
        ),
    ]
